FROM google/python
MAINTAINER SysOps "sysops@hugeinc.com"

#RUN useradd -ms /bin/bash stormy

RUN echo "deb http://pkg.jenkins-ci.org/debian binary/" >> /etc/apt/sources.list
RUN apt-get update && apt-get install wget curl -y

#ENV HOME /home/stormy

RUN mkdir -p /app/stormy-flask/app

WORKDIR /app
RUN virtualenv /env



ADD ./app/ /home/stormy/stormy-flask/app
ADD ./stormy_app.py /home/stormy/stormy-flask/
ADD ./requirements.txt /home/stormy/stormy-flask/
RUN pip install -r /home/stormy/stormy-flask/requirements.txt

USER stormy

# Change the working director to the app
WORKDIR /home/stormy/stormy-flask

#Run the Celery Batch Job
CMD celery -A stormy_app.celery worker --loglevel=info --beat --master_kube_ip=$MASTERKUBEIP

# Run the Flask Server
#CMD python stormy_app.py --master_kube_ip $MASTERKUBEIP


EXPOSE 5000
