FROM google/python
MAINTAINER SysOps "sysops@hugeinc.com"

RUN mkdir -p /home/stormy/stormy-flask/app
RUN mkdir -p /home/stormy/stormy-flask/celery


ADD ./app/ /home/stormy/stormy-flask/app
ADD ./stormy_app.py /home/stormy/stormy-flask/
ADD ./requirements.txt /home/stormy/stormy-flask/

# Change the working director to the app
WORKDIR /home/stormy/stormy-flask

RUN virtualenv env
RUN env/bin/pip install -r requirements.txt

#RUN source env/bin/activate


#Run the Celery Batch Job
#CMD celery -A stormy_app.celery worker --loglevel=info --beat --master_kube_ip=$MASTERKUBEIP -l info -n name --logfile=celery/celery.log --pidfile=celery/celery.log --schedule=celery/beat.db

# Run the Flask Server
#CMD python stormy_app.py --master_kube_ip $MASTERKUBEIP


EXPOSE 5000
